spring.application.name=NexChat
# Server configuration
server.port=8080
# Database configuration
spring.datasource.url = jdbc:postgresql://localhost:5432/db_nexchat
spring.datasource.username = postgres
spring.datasource.password = 629232
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.drivar-class-name=org.postgresql.Driver

